### ISSUE TITLE
further translations

### ISSUE THREAD

**Issue by Lezka212** [MrRedstoneToGo/Create-Bamboo-Sky#1]
I suggest adding "ESSENTIAL Mod" for cooperative play by licensed players
(written with the help of a translator, the translation may not be correct)

**Comment by MrRedstoneToGo** [comment]
I think ESSENTIAL is a bit cluttered with its marketplace and cosmetics and stuff, but what I might add is e4mc, this mod just gives you an IP address when you open the world on LAN. You can then send it to your friends so they can join your world.

Whose translations may not be correct?
1. from ESSENTIAL: It's just a utility mod and rather their problem than mine
2. in my modpack: please let me know where (Sometimes I also used a translator for better expressions)
3. your text: as long as I understand you, everything's fine :-)

**Comment by VladBezs** [comment]
![изображение_2024-06-21_112830232](https://github.com/MrRedstoneToGo/Create-Bamboo-Sky/assets/92430481/ffcb8eaa-b835-4f1a-b380-aeb93db491cb)
why hostile mobs do not appear on the island (in my case the farm does not work)

**Comment by MrRedstoneToGo** [comment]
This is intentional. I turned off mob spawning in the overworld because animal spawning gives the player the feeling that they must have lived there for a very long time, or in the case of hostile mobs, that they are being resurrected from the soul of a living creature from the past. But in a Skyblock world, where would the creatures come from? But I still let mobs spawn in the Nether, because it's the NETHER.
This also has the side effect that you NEED to create everything with create methods.
Sorry, you've built the farm and now it's useless.
Maybe I should put this feature in the pack description...

**Comment by VladBezs** [comment]
Yes, it’s better that it’s in the description because I think there will be a lot of reports about it (well, I went to translate the assembly into Russian and Ukrainian)

**Comment by MrRedstoneToGo** [comment]
Great, but please make sure to include all spaces and line breaks in the translation.

By the way, I have added this to the description:
> **Mob spawning:**
> Since I don't want Skyblock to depend on mob farms for the most part, I decided to disable mob spawning in the overworld. But beware, there are still Phantoms and Wandering Traders!
> Instead, the 1.20 Sniffer will dig for animal spawn eggs.
> 
> The Nether still contains mob spawn as it is supposed to be a dangerous dimension. Especially for Blazes, I added a new recipe for their spawn egg to make Blaze Burners easier to farm.

**Comment by VladBezs** [comment]
[ru_RU.json](https://github.com/user-attachments/files/15933013/ru_RU.json)
Hurray, I finished the Russian translation, maybe tomorrow I’ll do another Ukrainian one

**Comment by VladBezs** [comment]
I also wanted to ask if translation into other languages ​​is needed (Ukrainian Polish French)

**Comment by MrRedstoneToGo** [comment]
This is not necessary, but it's also a sign for me that the modpack is important enough for you to make translations for it.
That makes me very happy :-)
Go ahead!

**Comment by MrRedstoneToGo** [comment]
I changed something in the language files (https://github.com/MrRedstoneToGo/Create-Bamboo-Sky/commit/f0e9374aa6b868a85bac7a6b3b7011c2ab82f784). Please update ru_ru.json.

**Comment by MrRedstoneToGo** [comment]
How far along are you and when do you expect to be finished? I'm just asking to decide whether or not I should include the Russian (updated), Ukrainian, Polish and/or French translations in the next release.

**Comment by MrRedstoneToGo** [comment]
I added now
"%sСтеклянные бутылки можно получить, выпив выловленные бутылки с водой пустыми." at ru_ru.json and
"%sСкляні пляшки можна отримати, випивши порожніми виловлені пляшки з-під води." at uk_ua.json.
(this is what deepl.com spit out for me)

**Comment by MrRedstoneToGo** [comment]
Both files are now in this repository. If you accept the changes, I'll upload a new version of the modpack on modrinth.

**Comment by FrizingPaw** [comment]
> I added now "%sСтеклянные бутылки можно получить, выпив выловленные бутылки с водой пустыми." at ru_ru.json and "%sСкляні пляшки можна отримати, випивши порожніми виловлені пляшки з-під води." at uk_ua.json. (this is what deepl.com spit out for me)

That's right
"%sСтеклянные бутылки можно получить, выпив выловленные бутылки с водой." at ru_ru.json and
"%sСкляні пляшки можна отримати, випивши виловлені пляшки з-під води." at uk_ua.json.
thank you ^-^

**Comment by MrRedstoneToGo** [comment]
So, the new update is out. I added Supplementaries, so I had to add new entries (see changelog) in the language file for Russian and Ukrainain. I translated them to the respective languages using deepl. If you have a better idea for those, please let me know.
New translations are also highly sought after.
For now I close this issue.
