### ISSUE TITLE
Change/Simplify slime crafting

### ISSUE THREAD

**Issue by FrizingPaw** [MrRedstoneToGo/Create-Bamboo-Sky#2]
I offer Change/Simplify slime crafting, Because it is complicated.
Lime dye is difficult to obtain.
Or I just haven't found an easier recipe (Beat it when growing plants with bone meal. (Wild onion, wild tomato).
(written with the help of a translator, the translation may not be correct)

**Comment by MrRedstoneToGo** [comment]
I see, what should be an alternative recipe? maybe pressing/milling/cutting bamboo?

**Comment by MrRedstoneToGo** [comment]
I've added a new recipe for cutting bamboo, so now when you place bamboo on a cutting board, you'll get 1 tree bark and a 10% chance of getting lime dye. Obtaining lime dye is now much easier, and you don't have tons of stripped bamboo blocks in your chest.

**Comment by FrizingPaw** [comment]
Sorry. But I think you shouldn't do that.
It is better not to change the bamboo craft (Let the straw and the cut bamboo block fall out further).
1. Blocks can be used for further construction and crafting
2. It will not be so much and will not clog the chests (Just make several chests for it)
3. Will greatly simplify the production of mucus.

I propose to add the possibility of obtaining lime dye from an ordinary tomato bush with a 10% chance (It will be easier than what is. And more difficult than the previous option)

(written with the help of a translator, the translation may not be correct)

> I've added a new recipe for cutting bamboo, so now when you place bamboo on a cutting board, you'll get 1 tree bark and a 10% chance of getting lime dye. Obtaining lime dye is now much easier, and you don't have tons of stripped bamboo blocks in your chest.

**Comment by FrizingPaw** [comment]
Found a simple product)
fern + millstone = green dye
green dye + white dye = lime dye)
Sorry for the wasted time :(

**Comment by MrRedstoneToGo** [comment]
Yes, I saw it too. It requires some iron for the shears, but you also need shears for Thatch, so the iron isn't completely wasted. I will remove the new recipe.
