### ISSUE TITLE
Honey bottle

### ISSUE THREAD

**Issue by FrizingPaw** [MrRedstoneToGo/Create-Bamboo-Sky#3]
Can't be done honey bottle.
There is a task for which you need: honey bottle.
But you can't make a bottle.
You need sand(glass) to make a bottle.
Sand you can get only through chrushing wheel.
To do chrushing wheel necessary: mechanical creafter.
To do mechanical creafter necessary: electron tube
To do electron tube necessary: polished roza quartz
To do polished roza quartz necessary: sand paper 
Which is crafted from sand

Offers
1. Add craft sand through milstone or
2. Break gravel with a shovel + shift

Also
Add the relevant achievement (For the extraction of glass (+ signature: "sand can be extracted..."))

(written with the help of a translator, the translation may not be correct)

**Comment by MrRedstoneToGo** [comment]
Fish a water bottle.

**Comment by MrRedstoneToGo** [comment]
I also just added a tip in the advancements (will be included in the next release).

**Comment by FrizingPaw** [comment]
> I also just added a tip in the advancements (will be included in the next release).

Thank you, sorry for the wasted time.

**Comment by MrRedstoneToGo** [comment]
It wasn't completely wasted. You just brought me to call this in the advancements. The two "wasted time" issues shouldn't make you stop asking questions either. After all, I know where there are problems of understanding. 

PS: I actually pondered for a long time when creating the modpack how to do this with the glass bottles without making a lot of resources useless. (Sand washing -> clay balls -> copper; Red Sand washing -> gold.) The fact that you can also simply fish for the bottles made things a lot easier for me.
