### ISSUE TITLE
Unclear Slicer/Gravel interaction

### ISSUE THREAD

**Issue by BeeUhTrice** [MrRedstoneToGo/Create-Bamboo-Sky#4]
Hey! Having fun with the pack so far, but I can't get any combination of tools/item position/use of cutting board to get the gravel to cut automatically. The block said too slow and wrong direction, so i fixed those and I still can't get it to work. I looked and I couldn't find any documentation on this online, on the mod page, or in-game, so I'm kind of stuck.
![2024-07-11_16 01 22](https://github.com/user-attachments/assets/f94329a1-fb4b-4893-8aa0-371ad0b65521)

**Comment by BeeUhTrice** [comment]
Got it to work using a depot!

**Comment by MrRedstoneToGo** [comment]
Only the mechanical press can work without a depot/belt/basin.
