### ISSUE TITLE
Mobs do not spawn.

### ISSUE THREAD

**Issue by Common-Architect** [MrRedstoneToGo/Create-Bamboo-Sky#6]
I am trying to obtain string and other hostile mob drops, but mobs just wont spawn anywhere. Is this a feature?

**Comment by MrRedstoneToGo** [comment]
Yes, as explained in the description of this pack on Modrinth.

**Comment by MrRedstoneToGo** [comment]
Oh, and string comes from flax; see advancements of verion 3.0.0
