### ISSUE TITLE
The Huge Crafting Paradox

### ISSUE THREAD

**Issue by Toxopid2** [MrRedstoneToGo/Create-Bamboo-Sky#7]
(warning: there is a lot of toftology and there may be translation errors, I am bad at English)

To get netherack, need to cool magma by airing it on a fan that blows through powder snow. it, in turn, is obtained by adding 4 frosts (sugar + snowball) to a bucket. but it is impossible to get the snow itself. there is only one biome in the whole world, and its temperature does not allow snow to fall in the rain, even at an Y:319. that is, it is possible that the snow will get only from creative.

- But there is Frost Walker, you just need to enchant boots and break the ice with a silk touch!

1. leather cannot be getted. in order for us to have cows, we need a sniffer, and its egg is impossible to get. 
This can be solved by adding a recipe with crushing sand in a millstone, from which sandstone is made, and then its smooth version, which needs to be ground and a suspicious sand will turn out, when washed, there will be a chance to get a sniffer egg. this idea is from create live 5, and I think it sounds quite interesting.

2. diamonds for the enchantment table are also impossible to obtain, in order to crush a block of coal, coal is needed, it in turn is done by compressing its woody variation, attention, under heating. How do we get blaze burner that needs snow, that needs ice, that needs enchantment table, that needs diamonds, that needs coal, that needs heating, that needs a blaze burner? 
 
5. crushing wheels, brass for crafting which also requires heating, and copper is made of veridium or clay, both materials cannot be getted without the same wheels

4. rose quartz can be traded with piglins. that's just where the need to farm gold from zombie piglins comes into force until there is an ocrum. which is also impossible to get, because it is impossible to get lava, because the flare burner.. I've already discussed it.

**Comment by MrRedstoneToGo** [comment]
1. Fish your boots (junk) and the sniffer egg (treasure). (Btw I also followed Create Live 5)
2. The Enchanting Table is actually a thing, totally forgot about that! Thank you very much.
3. Place Mud on Dripstone Blocks with Pointed Dripstones underneath. The Mud will turn into a Clay Block.
4. Thought about milling Terracotta from Clay?

Conclusion: Some essential parts of the modpack require really deep knowledge of vanilla minecraft to get them. I'm going to start a trailer for this pack, I think many things will be much clearer afterwards.
The fact that Enchantment Tables are unobtainable yet, is a huge problem. I try to find a solution for this as soon as possible.

PS: Did you have any problems with Phantoms or an extremely slow filling Cauldron?

**Comment by Toxopid2** [comment]
Everything is okay except clay. Do you seriously propose to wait for a merchant (whom I have never seen in 150 hours in the game, even if 130 of them are waiting for water) with the necessary bidding for several hundred or even thousands of hours? And then spend several tens of hours on clay? even more so, not so much clay will give us, because for brass, without which it is impossible to get zinc along the chain of dependencies, and therefore brass, and (another huge chain of dependencies)

about P.S.: yep. It is not so difficult to get flax, but in order for this to happen before the phantoms appear, you need to set this goal for yourself from the first seconds, and continuously go towards it. Which will not help anyway, because the boiler in those 130 hours was not only not filled, not a single water level appeared. So I just took a bucket of water from creative and turned off DoInsomia , well, I'm too sick of it

**Comment by MrRedstoneToGo** [comment]
Clay should NOT depend on the red merchant. In general, no resource should need the latter one or Wandering Traders. And that you have to wait thousands of hours is more a side effect of the nearly unobtainablility of Powder Snow (Freeze Magma Block -> Netherrack -> Empty Blaze Burner -> Blaze Burner -> ... -> Biofuel -> Lava (+ Honey) -> Limestone -> Dripstone (+ Mud) -> Clay) and NOT A FEATURE. I don't want you to grind for nothing.
By the way, you can fish Enchanted Books and combine them with the respective item using an Anvil. 

about PS: Maybe a compacting recipe (eg. Leaves / Bamboo / Mulch) for water would be better? Or just 5 Cauldrons instead of 1. A very effective method against Phantoms is to build a platform above your head. They won't spawn anymore.

**Comment by Toxopid2** [comment]
OK, I'll just wait for your decision about the snow. if anything, can you get a bucket of honey without a dispenser? otherwise, I never got to honey, I just never found an oak tree with a beehive. 

yes, but without sculk sensor or mod for auto fishing(which is obviously cheat) this will make the player spend hours for fishing. and it will not be possible to automate before getting brass. I understand, gameplay is worth dragging out, but not that much. all these micro chances for some necessary event, the chance for some rare item without which you cannot advance, all this is the lot of typical OG modpacks, especially since the chance to get these two enchantments is small, because books are selected from the pool of enchantments of the table from level 30, and priority is given to some kind of efficiency or smite

yes, it definitely makes sense. a kind of tribute to the traditions of modified skyblocks. if I understood correctly, you want to make a recipe using a mechanical press, which, if there are greens in the bowl, will release some water. and you can add probability that 5 mlb of water will be obtained from 5 or 8 block of leaves is 50-25%. it will make you sweat, and there will be less element of randomness in it (I hate randomness, and it's honestly mutual).
I know about the protection from phantoms with a roof. I like it better when it's open, although I used to be a follower of hidden bases in the mountains. what about turn on doinsomnia when player receives water, and hint to the player that it is desirable to start creating a bed? but it's a little casual..

**Comment by MrRedstoneToGo** [comment]
the new version 3.1.0 is out! I've made some changes I didn't tell you:
Water can be easily collected now by placing Rain Gutters in the rain. They fill up with water very quickly (within one rain shower) and can be emptied directly with a bucket. I think it is now definitely possible to get a bed within the first 3 minecraft days. And if not, you can always build a roof until your bed is ready, which shouldn't take that long.
Powder Snow can now be obtained directly by placing cauldrons at altitudes where it can snow (I think y > 215?) You'll need a few of them, but you'll have enough iron by this point. Also, you no longer need to fish MANY enchanted books to get the right enchantment.
As a side note, even Calibrated Sculk Sensors output the same redstone signal strength when the fish bait produces bubbles and when you actually catch a fish. Fish farming is therefor completely based on luck.

I hope you like these changes and would love to hear your (hopefully not too bad) feedback!

**Comment by MrRedstoneToGo** [comment]
Oh, and Bee Nests grow on Cherry Trees with a 20% chance (modified) because they have so many blossoms. This behavior is already explained in the "Buzzy Trees" advancement.

**Comment by Toxopid2** [comment]
I've tested all the ideas you mentioned, everything works fine! despite the fact that the idea of sewerage is a little unbalanced, but, unlike it, we can say that water is a fundamental part of a skyblock, and the delay in getting it is, to put it mildly, the idea of psychos who like to watch other people suffer, and whose recommendations on YouTube like: "100 DAYS IN THE MOST DIFFICULT MINECRAFT HARDCORE SKYBLOCK", "I SPENT (H) HOURS CREATING (M) IN HARDCORE MINECRAFT SKYBLOCK".

if several similar videos about this modpack are not published, my life will be in vain, lol
I think I'll close this issue, all problems are solved.
